name: cleanup
on:
  push:
    branches:
      - master
jobs:
  test-cleanup:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: create bug
        run: make bug
        
      - name: create file
        run: make normal
      
      - name: create bug
        run: make bug

      - name: print 
        run: make print
      
      - name: cleanup
        if: ${{ always() }}
        run: make cleanup